# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  fetch:
    cmd: python3 stages/fetch_data.py
    deps:
      - stages/fetch_data.py
    outs:
      - brick/cebs_DDT_datasets.parquet
      - brick/datasets/
